add_stats – fpm-watch
add_stats Subroutine
MIT
6 statements
Source File
private subroutine add_stats(fm)
Factory helper: add the built-in stats feature.
Arguments
Type Intent Optional Attributes Name
type(feature_manager_t), intent(inout) :: fm
Calls
Called by
Source Code
   subroutine add_stats(fm)
      type(feature_manager_t), intent(inout) :: fm
      class(watch_feature_t), allocatable :: f
      call new_stats_feature(f)
      call fm%add(f)
   end subroutine add_stats
Call graph
add_stats calls fm_add, new_stats_feature
enable_features calls add_stats
watcher_init calls enable_features