apply_watch_from_manifest – fpm-watch
apply_watch_from_manifest Subroutine
MIT
23 statements
Source File
public subroutine apply_watch_from_manifest(w)
Apply configuration overrides from fpm.toml [extra.fpm-watch].
Missing keys are ignored; successfully read values override existing defaults.
Arguments
Type Intent Optional Attributes Name
type(watch_opts_t), intent(inout) :: w
Calls
Called by
Source Code
   subroutine apply_watch_from_manifest(w)
      type(watch_opts_t), intent(inout) :: w
      type(toml_table), allocatable :: root
      type(toml_table), pointer :: wt
      logical :: ok
      call load_watch_table(root, wt, ok)
      if (.not. ok) return
      call toml_get_real(wt,    "poll",     w%poll)
      call toml_get_real(wt,    "debounce", w%debounce)
      call toml_get_real(wt,    "rescan",   w%rescan)
      call toml_get_logical(wt, "debug",        w%debug)
      call toml_get_logical(wt, "print-files",  w%print_files_once)
      call toml_get_logical(wt, "silent-fpm",   w%silent_fpm)
      call toml_get_logical(wt, "run-on-start", w%run_on_start)
      call toml_get_logical(wt, "deps",         w%watch_deps)
      call toml_get_logical(wt, "low-cpu",      w%low_cpu)
      call toml_get_logical(wt, "once",         w%once)
      call toml_get_int(wt,     "verbosity", w%verbosity)
      call toml_get_list_strings(wt, "ignore",   w%ignore)
      call toml_get_list_strings(wt, "include",  w%include)
      call toml_get_list_strings(wt, "features", w%enabled_features)
      call normalize_watch_opts(w)
   end subroutine apply_watch_from_manifest
Call graph
apply_watch_from_manifest calls load_watch_table, normalize_watch_opts, toml_get_int, toml_get_list_strings, toml_get_logical, toml_get_real
load_watch_table calls exists, get_value, read_package_file
toml_get_int calls get_value
toml_get_list_strings calls get_list
toml_get_logical calls get_value
toml_get_real calls get_value
parse_cli calls apply_watch_from_manifest
parse_cli_config calls parse_cli