contains_path_fragment – fpm-watch
contains_path_fragment Function
MIT
15 statements
Source File
private pure function contains_path_fragment(p, frag) result(ok)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: p
character(len=*), intent(in) :: frag
Return Value logical
Calls
Called by
Source Code
   pure logical function contains_path_fragment(p, frag) result(ok)
      character(len=*), intent(in) :: p, frag
      character(len=:), allocatable :: needle
      ok = .false.
      if (len_trim(frag) == 0) return
      needle = "/" // trim(frag) // "/"
      if (index(p, needle) /= 0) then
         ok = .true.
         return
      end if
      if (ends_with(p, "/" // trim(frag))) then
         ok = .true.
         return
      end if
   end function contains_path_fragment
Call graph
contains_path_fragment calls ends_with
is_ignored_path calls contains_path_fragment
vec_push_unique calls is_ignored_path
gather_files_with_mask calls vec_push_unique
push_file_with_mask calls vec_push_unique
compute_watch_files_from_settings calls gather_files_with_mask, push_file_with_mask
rebuild_watch_list calls compute_watch_files_from_settings
handle_manifest_change calls rebuild_watch_list
watcher_init calls rebuild_watch_list
watcher_run calls rebuild_watch_list, handle_manifest_change