feat_after_noop – fpm-watch
feat_after_noop Subroutine
MIT
9 statements
Source File
private subroutine feat_after_noop(self, exitstat, seconds)
No-op callback invoked after executing the command.
Type Bound
watch_feature_t
Arguments
Type Intent Optional Attributes Name
class(watch_feature_t), intent(inout) :: self
integer, intent(in) :: exitstat
real, intent(in) :: seconds
Called by
Source Code
   subroutine feat_after_noop(self, exitstat, seconds)
      class(watch_feature_t), intent(inout) :: self
      integer, intent(in) :: exitstat
      real,    intent(in) :: seconds
      if (.false.) then
         if (exitstat /= 0) continue
         if (seconds < 0.0) continue
      end if
   end subroutine feat_after_noop
Call graph
on_after_run_all calls feat_after_noop
run_once calls on_after_run_all
watcher_run calls on_after_run_all
watcher_init calls run_once