find_ptr_index – fpm-watch
find_ptr_index Function
MIT
13 statements
Source File
private function find_ptr_index(p, all) result(idx)
Uses
fpm_targets
Arguments
Type Intent Optional Attributes Name
type(build_target_t), intent(in), pointer :: p
type(build_target_ptr), intent(in) :: all(:)
Return Value integer
Called by
Source Code
   integer function find_ptr_index(p, all) result(idx)
      use fpm_targets, only: build_target_t
      type(build_target_t), pointer, intent(in) :: p
      type(build_target_ptr), intent(in) :: all(:)
      integer :: i
      idx = 0
      do i = 1, size(all)
         if (associated(all(i)%ptr, p)) then
            idx = i
            return
         end if
      end do
   end function find_ptr_index
Call graph
dfs_mark_bool calls find_ptr_index, dfs_mark_bool
dfs_mark_mask calls find_ptr_index, dfs_mark_mask
compute_watch_files_from_settings calls dfs_mark_bool, dfs_mark_mask
rebuild_watch_list calls compute_watch_files_from_settings
handle_manifest_change calls rebuild_watch_list
watcher_init calls rebuild_watch_list
watcher_run calls rebuild_watch_list, handle_manifest_change