fnv1a_mix_str – fpm-watch
fnv1a_mix_str Subroutine
MIT
8 statements
Source File
private subroutine fnv1a_mix_str(h, s)
Mix a string into a 64-bit FNV-1a state.
Arguments
Type Intent Optional Attributes Name
integer(kind=int64), intent(inout) :: h
character(len=*), intent(in) :: s
Calls
Called by
Source Code
   subroutine fnv1a_mix_str(h, s)
      integer(int64), intent(inout) :: h
      character(len=*), intent(in)  :: s
      integer :: i
      do i = 1, len_trim(s)
         call fnv1a_mix_i64(h, int(iachar(s(i:i)), int64))
      end do
   end subroutine fnv1a_mix_str
Call graph
fnv1a_mix_str calls fnv1a_mix_i64
manifest_key_from_files calls fnv1a_mix_str
handle_manifest_change calls manifest_key_from_files, rebuild_watch_list
rebuild_watch_list calls manifest_key_from_files
watcher_init calls rebuild_watch_list
watcher_run calls handle_manifest_change, rebuild_watch_list