fnv1a_mix_i64 – fpm-watch
fnv1a_mix_i64 Subroutine
MIT
6 statements
Source File
private subroutine fnv1a_mix_i64(h, x)
Mix a single 64-bit value into a 64-bit FNV-1a state.
Arguments
Type Intent Optional Attributes Name
integer(kind=int64), intent(inout) :: h
integer(kind=int64), intent(in) :: x
Called by
Source Code
   subroutine fnv1a_mix_i64(h, x)
      integer(int64), intent(inout) :: h
      integer(int64), intent(in)    :: x
      h = ieor(h, x)
      h = h * FNV_PRIME
   end subroutine fnv1a_mix_i64
Call graph
fnv1a_mix_str calls fnv1a_mix_i64
hash_block calls fnv1a_mix_i64
manifest_key_from_files calls fnv1a_mix_i64, fnv1a_mix_str, file_fingerprint
file_fingerprint calls hash_block
handle_manifest_change calls manifest_key_from_files, rebuild_watch_list
rebuild_watch_list calls manifest_key_from_files, init_fingerprints
init_fingerprints calls file_fingerprint
scan_changes calls file_fingerprint
watcher_init calls rebuild_watch_list
watcher_run calls handle_manifest_change, rebuild_watch_list, scan_changes