ftoa – fpm-watch
ftoa Function
MIT
7 statements
Source File
public pure function ftoa(x) result(s)
Format a real number with two decimal places.
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: x
Return Value character(len=:), allocatable
Called by
Source Code
   pure function ftoa(x) result(s)
      real, intent(in) :: x
      character(len=:), allocatable :: s
      character(len=64) :: buf
      write(buf,'(f0.2)') x
      s = trim(buf)
   end function ftoa
Call graph
compute_watch_files_from_settings calls ftoa
print_banner calls ftoa
rebuild_watch_list calls ftoa, compute_watch_files_from_settings, print_banner
report_changes calls ftoa
run_command_and_report calls ftoa
handle_manifest_change calls rebuild_watch_list
run_once calls run_command_and_report
watcher_init calls rebuild_watch_list, run_once
watcher_run calls rebuild_watch_list, report_changes, run_command_and_report, handle_manifest_change