get_arg – fpm-watch
get_arg Function
MIT
14 statements
Source File
public function get_arg(i) result(a)
Retrieve a command-line argument as an allocatable string.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: i
0-based/1-based index passed to get_command_argument.
Return Value character(len=:), allocatable
Called by
Source Code
   function get_arg(i) result(a)
      integer, intent(in) :: i
      !! 0-based/1-based index passed to `get_command_argument`.
      character(len=:), allocatable :: a
      integer :: n, istat
      n = 0
      call get_command_argument(i, length=n, status=istat)
      if (istat /= 0 .or. n <= 0) then
         a = ""
         return
      end if
      allocate(character(len=n) :: a)
      call get_command_argument(i, value=a, status=istat)
      if (istat /= 0) a = ""
   end function get_arg
Call graph
apply_watch_flag calls get_arg
build_child_command calls get_arg, choose_self_exe
choose_self_exe calls get_arg
join_argv calls get_arg
parse_cli calls get_arg, apply_watch_flag, join_argv
parse_restart_flags calls get_arg
maybe_supervise calls parse_restart_flags, supervisor_loop
parse_cli_config calls parse_cli
supervisor_loop calls build_child_command