handle_manifest_change – fpm-watch
handle_manifest_change Subroutine
MIT
11 statements
Source File
private subroutine handle_manifest_change(self)
Handle a manifest change (fpm.toml) by rebuilding the watch list.
This also notifies feature plugins via on_manifest_changed.
Arguments
Type Intent Optional Attributes Name
class(watcher_t), intent(inout) :: self
Calls
Called by
Source Code
   subroutine handle_manifest_change(self)
      class(watcher_t), intent(inout) :: self
      integer(int64) :: man_now
      man_now = manifest_key_from_files(self%cfg%settings, self%files)
      if (man_now /= self%man_prev) then
         call self%fm%on_manifest_changed_all(self%man_prev, man_now)
         self%man_prev = man_now
      end if
      call log_info(self%cfg%w, "manifest changed -> rebuilding watch list")
      call rebuild_watch_list(self, print_header=.false.)
   end subroutine handle_manifest_change
Call graph
handle_manifest_change calls log_info, manifest_key_from_files, on_manifest_changed_all, rebuild_watch_list
log_info calls colorize
manifest_key_from_files calls basename, features, file_fingerprint, fnv1a_mix_i64, fnv1a_mix_str
on_manifest_changed_all calls feat_manifest_noop
rebuild_watch_list calls log_info, manifest_key_from_files, compute_watch_files_from_settings, ftoa, init_fingerprints, on_watch_list_built_all, print_banner, print_file_list, str
compute_watch_files_from_settings calls log_info, basename, ftoa, str, add, build_model, dep, get_package_data, is_executable_target, join_path, new_dependency_tree, dfs_mark_bool, dfs_mark_mask, filter_watch_files, gather_files_with_mask, is_run_or_test, normalize_path, push_file_with_mask, select_names_or_all, trim_or_empty, targets_from_sources
file_fingerprint calls hash_block
fnv1a_mix_str calls fnv1a_mix_i64
init_fingerprints calls file_fingerprint
on_watch_list_built_all calls feat_list_noop
print_banner calls colorize, ftoa, str, active_features, active_profile, command_mode, trim_or_default
print_file_list calls colorize, str
active_features calls join_csv
active_profile calls trim_or_default
dfs_mark_bool calls dfs_mark_bool, dependencies, find_ptr_index
dfs_mark_mask calls dfs_mark_mask, dependencies, find_ptr_index
filter_watch_files calls basename, normalize_path, glob
gather_files_with_mask calls include_dependencies, vec_push_unique
hash_block calls fnv1a_mix_i64
push_file_with_mask calls vec_push_unique
select_names_or_all calls basename, is_executable_target, glob
vec_push_unique calls normalize_path, exists, is_ignored_path, is_in_dep_dirs, vec_grow
is_ignored_path calls normalize_path, contains_path_fragment, starts_with
is_in_dep_dirs calls normalize_path, starts_with
contains_path_fragment calls ends_with
watcher_run calls handle_manifest_change