is_in_dep_dirs – fpm-watch
is_in_dep_dirs Function
MIT
22 statements
Source File
private pure function is_in_dep_dirs(p, dep_dirs) result(ok)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: p
type(string_t), intent(in), allocatable :: dep_dirs(:)
Return Value logical
Calls
Called by
Source Code
   pure logical function is_in_dep_dirs(p, dep_dirs) result(ok)
      character(len=*), intent(in) :: p
      type(string_t), allocatable, intent(in) :: dep_dirs(:)
      integer :: j
      character(len=:), allocatable :: d
      ok = .false.
      if (.not. allocated(dep_dirs)) return
      if (size(dep_dirs) == 0) return
      do j = 1, size(dep_dirs)
         if (len_trim(dep_dirs(j)%s) == 0) cycle
         d = normalize_path(trim(dep_dirs(j)%s))
         if (len_trim(d) == 0) cycle
         if (p == d) then
            ok = .true.
            return
         end if
         if (starts_with(p, d // "/")) then
            ok = .true.
            return
         end if
      end do
   end function is_in_dep_dirs
Call graph
is_in_dep_dirs calls normalize_path, starts_with
vec_push_unique calls is_in_dep_dirs
gather_files_with_mask calls vec_push_unique
push_file_with_mask calls vec_push_unique
compute_watch_files_from_settings calls gather_files_with_mask, push_file_with_mask
rebuild_watch_list calls compute_watch_files_from_settings
handle_manifest_change calls rebuild_watch_list
watcher_init calls rebuild_watch_list
watcher_run calls rebuild_watch_list, handle_manifest_change