is_windows_os – fpm-watch
is_windows_os Function
MIT
3 statements
Source File
public function is_windows_os()
Return whether the current OS should be treated as Windows for quoting.
Arguments
None
Return Value logical
Calls
Called by
Source Code
   logical function is_windows_os()
      is_windows_os = (get_os_type() == OS_WINDOWS)
   end function is_windows_os
Call graph
is_windows_os calls get_os_type
quote_arg calls is_windows_os
build_child_command calls quote_arg
join_argv calls quote_arg
parse_cli calls join_argv
supervisor_loop calls build_child_command
maybe_supervise calls supervisor_loop
parse_cli_config calls parse_cli