join_argv – fpm-watch
join_argv Function
MIT
17 statements
Source File
public function join_argv(i1, i2) result(s)
Join a range of argv entries into a single command-line string.
Each token is quoted when needed, using quote_arg(); quoting rules are platform-dependent (Windows vs POSIX).
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: i1
Inclusive range of argv indices to join.
integer, intent(in) :: i2
Inclusive range of argv indices to join.
Return Value character(len=:), allocatable
Calls
Called by
Source Code
   function join_argv(i1, i2) result(s)
      integer, intent(in) :: i1, i2
      !! Inclusive range of argv indices to join.
      character(len=:), allocatable :: s
      character(len=:), allocatable :: a
      integer :: i
      s = ""
      do i = i1, i2
         a = get_arg(i)
         if (len_trim(a) == 0) cycle
         if (needs_quotes(a)) then
            s = s // quote_arg(a) // " "
         else
            s = s // trim(a) // " "
         end if
      end do
      s = trim(s)
   end function join_argv
Call graph
join_argv calls get_arg, needs_quotes, quote_arg
quote_arg calls is_windows_os
is_windows_os calls get_os_type
parse_cli calls join_argv
parse_cli_config calls parse_cli