load_watch_table – fpm-watch
load_watch_table Subroutine
MIT
21 statements
Source File
private subroutine load_watch_table(root, wt, ok)
Locate and return the [extra.fpm-watch] table from fpm.toml.
Returns ok=.false. when: - fpm.toml is missing, - the TOML cannot be read, - the extra table is absent, - the fpm-watch table is absent.
Arguments
Type Intent Optional Attributes Name
type(toml_table), intent(out), allocatable :: root
type(toml_table), intent(out), pointer :: wt
logical, intent(out) :: ok
Calls
Called by
Source Code
   subroutine load_watch_table(root, wt, ok)
      type(toml_table), allocatable, intent(out) :: root
      type(toml_table), pointer, intent(out) :: wt
      logical, intent(out) :: ok
      type(toml_table), pointer :: extra
      type(error_t), allocatable :: err
      integer :: stat
      ok = .false.
      wt => null()
      extra => null()
      if (.not. exists("fpm.toml")) return
      call read_package_file(root, "fpm.toml", err)
      if (allocated(err)) return
      call get_value(root, "extra", extra, requested=.false., stat=stat)
      if (stat /= toml_stat%success) return
      if (.not. associated(extra)) return
      call get_value(extra, "fpm-watch", wt, requested=.false., stat=stat)
      if (stat /= toml_stat%success) return
      if (.not. associated(wt)) return
      ok = .true.
   end subroutine load_watch_table
Call graph
load_watch_table calls exists, get_value, read_package_file
apply_watch_from_manifest calls load_watch_table
get_restart_defaults calls load_watch_table
parse_cli calls apply_watch_from_manifest
parse_restart_flags calls get_restart_defaults
maybe_supervise calls parse_restart_flags
parse_cli_config calls parse_cli