log_info – fpm-watch
log_info Subroutine
MIT
6 statements
Source File
public subroutine log_info(w, msg)
Log an informational message.
Arguments
Type Intent Optional Attributes Name
type(watch_opts_t), intent(in) :: w
character(len=*), intent(in) :: msg
Calls
Called by
Source Code
   subroutine log_info(w, msg)
      type(watch_opts_t), intent(in) :: w
      character(len=*), intent(in)   :: msg
      if (w%verbosity < 0) return
      write(output_unit,'(a)') &
         colorize("info       |", color_fg='blue_intense', style='bold_on') // "  " // trim(msg)
   end subroutine log_info
Call graph
log_info calls colorize
compute_watch_files_from_settings calls log_info
handle_manifest_change calls log_info, rebuild_watch_list
rebuild_watch_list calls log_info, compute_watch_files_from_settings
stats_init calls log_info
watcher_run calls log_info, handle_manifest_change, rebuild_watch_list
watcher_init calls rebuild_watch_list