maybe_supervise – fpm-watch
maybe_supervise Subroutine
MIT
11 statements
Source File
public subroutine maybe_supervise()
Enter supervisor mode when requested, otherwise return immediately.
If auto-restart is enabled and the current process is not marked as a child (--watch-child), this routine runs a supervisor loop and does not return.
Arguments
None
Calls
Source Code
   subroutine maybe_supervise()
      logical :: auto_restart, is_child
      real    :: restart_delay
      integer :: restart_max
      character(len=:), allocatable :: self_exe
      call parse_restart_flags(auto_restart, restart_delay, restart_max, is_child, self_exe)
      if (auto_restart .and. (.not. is_child)) then
         call supervisor_loop(max(0.0, restart_delay), restart_max, self_exe)
         stop 0
      end if
   end subroutine maybe_supervise
Call graph
maybe_supervise calls parse_restart_flags, supervisor_loop
parse_restart_flags calls get_arg, get_restart_defaults, parse_int, parse_real, set_low_cpu, starts_with
supervisor_loop calls build_child_command, sleep_seconds
build_child_command calls get_arg, starts_with, choose_self_exe, quote_arg
get_restart_defaults calls load_watch_table, toml_get_int, toml_get_logical, toml_get_real, toml_get_string
sleep_seconds calls sleep_os, sleep_spin
choose_self_exe calls get_arg
load_watch_table calls exists, get_value, read_package_file
quote_arg calls is_windows_os
sleep_os calls get_os_type, sleep_os_posix, sleep_os_win
toml_get_int calls get_value
toml_get_logical calls get_value
toml_get_real calls get_value
toml_get_string calls get_value
is_windows_os calls get_os_type
sleep_os_posix calls c_nanosleep
sleep_os_win calls c_sleep_ms