normalize_path – fpm-watch
normalize_path Function
MIT
16 statements
Source File
public pure function normalize_path(path) result(p)
Normalize a path to a consistent form for matching.
Transformations: - Backslashes (\) → slashes (/) - Strip any leading ./ prefixes (repeatedly)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: path
Return Value character(len=:), allocatable
Called by
Source Code
   pure function normalize_path(path) result(p)
      character(len=*), intent(in) :: path
      character(len=:), allocatable :: p
      integer :: i
      p = trim(path)
      do i = 1, len(p)
         if (p(i:i) == char(92)) p(i:i) = "/"
      end do
      do while (len(p) >= 2)
         if (p(1:2) == "./") then
            p = p(3:)
         else
            exit
         end if
      end do
   end function normalize_path
Call graph
compute_watch_files_from_settings calls normalize_path, filter_watch_files, gather_files_with_mask, push_file_with_mask
filter_watch_files calls normalize_path
is_ignored_path calls normalize_path
is_in_dep_dirs calls normalize_path
vec_push_unique calls normalize_path, is_ignored_path, is_in_dep_dirs
gather_files_with_mask calls vec_push_unique
push_file_with_mask calls vec_push_unique
rebuild_watch_list calls compute_watch_files_from_settings
handle_manifest_change calls rebuild_watch_list
watcher_init calls rebuild_watch_list
watcher_run calls rebuild_watch_list, handle_manifest_change