on_before_run_all – fpm-watch
on_before_run_all Subroutine
MIT
9 statements
Source File
private subroutine on_before_run_all(self, cmd)
Call on_before_run(cmd) on all registered features.
Type Bound
feature_manager_t
Arguments
Type Intent Optional Attributes Name
class(feature_manager_t), intent(inout) :: self
character(len=:), intent(inout), allocatable :: cmd
Calls
Called by
Source Code
   subroutine on_before_run_all(self, cmd)
      class(feature_manager_t), intent(inout) :: self
      character(len=:), allocatable, intent(inout) :: cmd
      integer :: i
      if (.not. allocated(self%feat)) return
      do i = 1, size(self%feat)
         if (allocated(self%feat(i)%p)) call self%feat(i)%p%on_before_run(cmd)
      end do
   end subroutine on_before_run_all
Call graph
on_before_run_all calls feat_before_noop
run_once calls on_before_run_all
watcher_run calls on_before_run_all
watcher_init calls run_once