parse_cli_config – fpm-watch
parse_cli_config Subroutine
MIT
12 statements
Source File
public subroutine parse_cli_config(cfg)
Uses
watch_cmdsplice
Parse CLI arguments and build the full watcher configuration.
Produces a watch_config_t: - cfg%w contains watcher options (polling, debounce, flags, etc.) - cfg%settings holds the typed fpm settings for the selected subcommand - cfg%fpm_cmdline is the effective command string - cfg%cmd_prefix and cfg%cmd_rest are helper fields used to inject target names into run/test commands.
Arguments
Type Intent Optional Attributes Name
type(watch_config_t), intent(out) :: cfg
Calls
Source Code
   subroutine parse_cli_config(cfg)
      use watch_cmdsplice, only: split_cmd_after_subcmd
      type(watch_config_t), intent(out) :: cfg
      character(len=:), allocatable :: fpm_cmdline
      class(fpm_build_settings), allocatable :: settings
      character(len=:), allocatable :: subcmd
      call parse_cli(cfg%w, settings, fpm_cmdline, subcmd)
      cfg%fpm_cmdline = fpm_cmdline
      cfg%subcmd      = subcmd
      call move_alloc(settings, cfg%settings)
      call split_cmd_after_subcmd(cfg%fpm_cmdline, cfg%cmd_prefix, cfg%cmd_rest)
   end subroutine parse_cli_config
Call graph
parse_cli_config calls parse_cli, split_cmd_after_subcmd
parse_cli calls add_features_csv, apply_watch_flag, apply_watch_from_manifest, default_build_dir, get_arg, init_build_settings, is_supported_subcmd, is_watch_flag, join_argv, normalize_watch_opts, push_feature, set_names, set_watch_defaults, usage_and_stop, usage_and_stop_ok
add_features_csv calls push_feature
apply_watch_flag calls get_arg, normalize_watch_opts, push_feature, usage_and_stop, usage_and_stop_ok, parse_int, parse_real
apply_watch_from_manifest calls normalize_watch_opts, load_watch_table, toml_get_int, toml_get_list_strings, toml_get_logical, toml_get_real
init_build_settings calls features
join_argv calls get_arg, needs_quotes, quote_arg
set_names calls name
usage_and_stop calls colorize, usage_print_only
usage_and_stop_ok calls usage_print_only
load_watch_table calls exists, get_value, read_package_file
quote_arg calls is_windows_os
toml_get_int calls get_value
toml_get_list_strings calls get_list
toml_get_logical calls get_value
toml_get_real calls get_value
usage_print_only calls colorize
is_windows_os calls get_os_type