rebuild_watch_list – fpm-watch
rebuild_watch_list Subroutine
MIT
39 statements
Source File
private subroutine rebuild_watch_list(self, print_header)
Recompute the watch list, rebuild fingerprints, and print/log the result.
Called: - During initialization, - When the manifest changes, - Periodically when rescan > 0.
Arguments
Type Intent Optional Attributes Name
class(watcher_t), intent(inout) :: self
logical, intent(in) :: print_header
Calls
Called by
Source Code
   subroutine rebuild_watch_list(self, print_header)
      class(watcher_t), intent(inout) :: self
      logical, intent(in) :: print_header
      integer(int64) :: rate, t0, t1
      real :: build_secs_total
      real :: secs_model, secs_targets, secs_watch
      integer :: nfiles, nroots
      real :: dummy_build
      type(string_t), allocatable :: new_files(:)
      integer(int64), allocatable :: new_mask(:)
      type(root_info_t), allocatable :: new_roots(:)
      call system_clock(count_rate=rate)
      if (rate <= 0_int64) rate = 1000_int64
      call system_clock(t0)
      call compute_watch_files_from_settings( &
         settings     = self%cfg%settings, &
         w            = self%cfg%w,        &
         files        = new_files,         &
         file_mask    = new_mask,          &
         roots        = new_roots,         &
         manifest_key = self%man_prev,     &
         build_secs   = dummy_build,       &
         secs_model   = secs_model,        &
         secs_targets = secs_targets,      &
         secs_watch   = secs_watch )
      call move_alloc(new_files, self%files)
      call move_alloc(new_mask,  self%file_mask)
      call move_alloc(new_roots, self%roots)
      call self%fm%on_watch_list_built_all(self%files, self%roots)
      self%man_prev = manifest_key_from_files(self%cfg%settings, self%files)
      call init_fingerprints(self%files, self%fp_prev, self%fp_now, self%changed_idx)
      call system_clock(t1)
      build_secs_total = real(t1 - t0) / real(rate)
      nfiles = 0
      if (allocated(self%files)) nfiles = size(self%files)
      nroots = 0
      if (allocated(self%roots)) nroots = size(self%roots)
      if (self%cfg%w%debug) then
         call log_info(self%cfg%w, "debug: manifest_key=" // str(self%man_prev))
         call log_info(self%cfg%w, "debug: roots=" // str(nroots) // " files=" // str(nfiles))
      end if
      if (print_header) then
         call print_banner( &
            full_cmdline = self%cfg%fpm_cmdline, &
            settings     = self%cfg%settings,    &
            w            = self%cfg%w,           &
            files        = self%files,           &
            build_secs   = build_secs_total,     &
            roots_count  = nroots,               &
            secs_model   = secs_model,           &
            secs_targets = secs_targets,         &
            secs_watch   = secs_watch )
         if (self%cfg%w%print_files_once) call print_file_list(self%files, self%cfg%w)
      else
         call log_info(self%cfg%w, "watch list updated in " // ftoa(build_secs_total) // "s; files=" // str(nfiles))
         if (self%cfg%w%verbosity >= 2) call print_file_list(self%files, self%cfg%w)
      end if
   end subroutine rebuild_watch_list
Call graph
rebuild_watch_list calls compute_watch_files_from_settings, ftoa, init_fingerprints, log_info, manifest_key_from_files, on_watch_list_built_all, print_banner, print_file_list, str
compute_watch_files_from_settings calls ftoa, log_info, str, add, basename, build_model, dep, get_package_data, is_executable_target, join_path, new_dependency_tree, dfs_mark_bool, dfs_mark_mask, filter_watch_files, gather_files_with_mask, is_run_or_test, normalize_path, push_file_with_mask, select_names_or_all, trim_or_empty, targets_from_sources
init_fingerprints calls file_fingerprint
log_info calls colorize
manifest_key_from_files calls basename, features, file_fingerprint, fnv1a_mix_i64, fnv1a_mix_str
on_watch_list_built_all calls feat_list_noop
print_banner calls ftoa, str, colorize, active_features, active_profile, command_mode, trim_or_default
print_file_list calls str, colorize
active_features calls join_csv
active_profile calls trim_or_default
dfs_mark_bool calls dfs_mark_bool, dependencies, find_ptr_index
dfs_mark_mask calls dfs_mark_mask, dependencies, find_ptr_index
file_fingerprint calls hash_block
filter_watch_files calls basename, normalize_path, glob
fnv1a_mix_str calls fnv1a_mix_i64
gather_files_with_mask calls include_dependencies, vec_push_unique
push_file_with_mask calls vec_push_unique
select_names_or_all calls basename, is_executable_target, glob
hash_block calls fnv1a_mix_i64
vec_push_unique calls normalize_path, exists, is_ignored_path, is_in_dep_dirs, vec_grow
is_ignored_path calls normalize_path, contains_path_fragment, starts_with
is_in_dep_dirs calls normalize_path, starts_with
contains_path_fragment calls ends_with
handle_manifest_change calls rebuild_watch_list
watcher_init calls rebuild_watch_list
watcher_run calls rebuild_watch_list, handle_manifest_change