run_once – fpm-watch
run_once Subroutine
MIT
11 statements
Source File
private subroutine run_once(self, cmd0)
Run the configured command once without change detection.
Used for the optional "run on start" behavior.
Arguments
Type Intent Optional Attributes Name
class(watcher_t), intent(inout) :: self
character(len=*), intent(in) :: cmd0
Calls
Called by
Source Code
   subroutine run_once(self, cmd0)
      class(watcher_t), intent(inout) :: self
      character(len=*), intent(in) :: cmd0
      character(len=:), allocatable :: cmd
      integer :: exitstat
      real :: secs
      cmd = trim(cmd0)
      call self%fm%on_before_run_all(cmd)
      call run_command_and_report(cmd, self%cfg%w, exitstat, secs)
      call self%fm%on_after_run_all(exitstat, secs)
   end subroutine run_once
Call graph
run_once calls on_after_run_all, on_before_run_all, run_command_and_report
on_after_run_all calls feat_after_noop
on_before_run_all calls feat_before_noop
run_command_and_report calls colorize, ftoa, run, str
watcher_init calls run_once