select_names_or_all – fpm-watch
select_names_or_all Subroutine
MIT
38 statements
Source File
private subroutine select_names_or_all(targets, scope, names, keep)
Arguments
Type Intent Optional Attributes Name
type(build_target_ptr), intent(in) :: targets(:)
integer, intent(in) :: scope
character(len=*), intent(in), optional :: names(:)
logical, intent(inout) :: keep(:)
Calls
Called by
Source Code
   subroutine select_names_or_all(targets, scope, names, keep)
      type(build_target_ptr), intent(in) :: targets(:)
      integer, intent(in) :: scope
      character(len=*), intent(in), optional :: names(:)
      logical, intent(inout) :: keep(:)
      integer :: i, j
      character(len=:), allocatable :: outbase_full, outbase_stem
      logical :: any_name
      any_name = .false.
      if (present(names)) then
         if (size(names) > 0) then
            do j = 1, size(names)
               if (len_trim(names(j)) > 0) then
                  any_name = .true.
                  exit
               end if
            end do
         end if
      end if
      if (.not. any_name) then
         do i = 1, size(targets)
            if (targets(i)%ptr%is_executable_target(scope)) keep(i) = .true.
         end do
         return
      end if
      do i = 1, size(targets)
         if (.not. targets(i)%ptr%is_executable_target(scope)) cycle
         outbase_full = basename(targets(i)%ptr%output_file)
         outbase_stem = basename(targets(i)%ptr%output_file, suffix=.false.)
         do j = 1, size(names)
            if (len_trim(names(j)) == 0) cycle
            if (glob(trim(names(j)), outbase_full) .or. glob(trim(names(j)), outbase_stem)) then
               keep(i) = .true.
               exit
            end if
         end do
      end do
   end subroutine select_names_or_all
Call graph
select_names_or_all calls basename, glob, is_executable_target
compute_watch_files_from_settings calls select_names_or_all
rebuild_watch_list calls compute_watch_files_from_settings
handle_manifest_change calls rebuild_watch_list
watcher_init calls rebuild_watch_list
watcher_run calls rebuild_watch_list, handle_manifest_change