set_low_cpu – fpm-watch
set_low_cpu Subroutine
MIT
4 statements
Source File
public subroutine set_low_cpu(flag)
Arguments
Type Intent Optional Attributes Name
logical, intent(in) :: flag
Called by
Source Code
   subroutine set_low_cpu(flag)
      logical, intent(in) :: flag
      low_cpu_mode = flag
   end subroutine set_low_cpu
Call graph
parse_restart_flags calls set_low_cpu
watcher_init calls set_low_cpu
maybe_supervise calls parse_restart_flags