sleep_os_posix – fpm-watch
sleep_os_posix Subroutine
MIT
25 statements
Source File
private subroutine sleep_os_posix(s)
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: s
Calls
Called by
Source Code
   subroutine sleep_os_posix(s)
      real, intent(in) :: s
      type(timespec) :: req, rem
      integer(c_int) :: rc
      real :: ss, frac
      integer(c_long) :: sec, nsec
      ss = s
      if (ss <= 0.0) return
      sec  = int(ss, kind=c_long)
      frac = ss - real(sec)
      if (frac < 0.0) frac = 0.0
      nsec = int(frac * 1000000000.0, kind=c_long)
      if (nsec < 0_c_long) nsec = 0_c_long
      if (nsec >= 1000000000_c_long) then
         sec = sec + 1_c_long
         nsec = nsec - 1000000000_c_long
      end if
      req%tv_sec  = sec
      req%tv_nsec = nsec
      do
         rc = c_nanosleep(req, rem)
         if (rc == 0_c_int) exit
         req = rem
      end do
   end subroutine sleep_os_posix
Call graph
sleep_os_posix calls c_nanosleep
sleep_os calls sleep_os_posix
sleep_seconds calls sleep_os
supervisor_loop calls sleep_seconds
watcher_run calls sleep_seconds
maybe_supervise calls supervisor_loop