usage_and_stop_ok – fpm-watch
usage_and_stop_ok Subroutine
MIT
4 statements
Source File
private subroutine usage_and_stop_ok()
Print a usage message and terminate successfully.
Arguments
None
Calls
Called by
Source Code
   subroutine usage_and_stop_ok()
      call usage_print_only()
      stop 0
   end subroutine usage_and_stop_ok
Call graph
usage_and_stop_ok calls usage_print_only
usage_print_only calls colorize
apply_watch_flag calls usage_and_stop_ok
parse_cli calls usage_and_stop_ok, apply_watch_flag
parse_cli_config calls parse_cli