vec_push_unique – fpm-watch
vec_push_unique Subroutine
MIT
28 statements
Source File
private subroutine vec_push_unique(buf, mbuf, n, cap, path, build_dir, mask, dep_dirs)
Arguments
Type Intent Optional Attributes Name
type(string_t), intent(inout), allocatable :: buf(:)
integer(kind=int64), intent(inout), allocatable :: mbuf(:)
integer, intent(inout) :: n
integer, intent(inout) :: cap
character(len=*), intent(in) :: path
character(len=*), intent(in) :: build_dir
integer(kind=int64), intent(in) :: mask
type(string_t), intent(in), optional, allocatable :: dep_dirs(:)
Calls
Called by
Source Code
   subroutine vec_push_unique(buf, mbuf, n, cap, path, build_dir, mask, dep_dirs)
      type(string_t), allocatable, intent(inout) :: buf(:)
      integer(int64), allocatable, intent(inout) :: mbuf(:)
      integer, intent(inout) :: n, cap
      character(len=*), intent(in) :: path
      character(len=*), intent(in) :: build_dir
      integer(int64), intent(in) :: mask
      type(string_t), allocatable, intent(in), optional :: dep_dirs(:)
      character(len=:), allocatable :: p
      integer :: i
      p = normalize_path(path)
      if (len_trim(p) == 0) return
      if (is_ignored_path(p, build_dir)) then
         if (.not. present(dep_dirs)) return
         if (.not. is_in_dep_dirs(p, dep_dirs)) return
      end if
      if (.not. exists(p)) return
      do i = 1, n
         if (buf(i)%s == p) then
            mbuf(i) = ior(mbuf(i), mask)
            return
         end if
      end do
      if (n >= cap) call vec_grow(buf, mbuf, cap)
      n = n + 1
      buf(n)%s = p
      mbuf(n) = mask
   end subroutine vec_push_unique
Call graph
vec_push_unique calls exists, is_ignored_path, is_in_dep_dirs, normalize_path, vec_grow
is_ignored_path calls normalize_path, contains_path_fragment, starts_with
is_in_dep_dirs calls normalize_path, starts_with
contains_path_fragment calls ends_with
gather_files_with_mask calls vec_push_unique
push_file_with_mask calls vec_push_unique
compute_watch_files_from_settings calls gather_files_with_mask, push_file_with_mask
rebuild_watch_list calls compute_watch_files_from_settings
handle_manifest_change calls rebuild_watch_list
watcher_init calls rebuild_watch_list
watcher_run calls rebuild_watch_list, handle_manifest_change