vec_grow – fpm-watch
vec_grow Subroutine
MIT
17 statements
Source File
private subroutine vec_grow(buf, mbuf, cap)
Arguments
Type Intent Optional Attributes Name
type(string_t), intent(inout), allocatable :: buf(:)
integer(kind=int64), intent(inout), allocatable :: mbuf(:)
integer, intent(inout) :: cap
Called by
Source Code
   subroutine vec_grow(buf, mbuf, cap)
      type(string_t), allocatable, intent(inout) :: buf(:)
      integer(int64), allocatable, intent(inout) :: mbuf(:)
      integer, intent(inout) :: cap
      type(string_t), allocatable :: nb(:)
      integer(int64), allocatable :: nm(:)
      integer :: newcap, i
      newcap = max(16, cap + cap/2)
      allocate(nb(newcap), nm(newcap))
      do i = 1, cap
         nb(i)%s = buf(i)%s
         nm(i) = mbuf(i)
      end do
      call move_alloc(nb, buf)
      call move_alloc(nm, mbuf)
      cap = newcap
   end subroutine vec_grow
Call graph
vec_push_unique calls vec_grow
gather_files_with_mask calls vec_push_unique
push_file_with_mask calls vec_push_unique
compute_watch_files_from_settings calls gather_files_with_mask, push_file_with_mask
rebuild_watch_list calls compute_watch_files_from_settings
handle_manifest_change calls rebuild_watch_list
watcher_init calls rebuild_watch_list
watcher_run calls rebuild_watch_list, handle_manifest_change