watcher_run – fpm-watch
watcher_run Subroutine
MIT
59 statements
Source File
private subroutine watcher_run(self)
Run the main watch loop until termination.
Termination conditions: - The sentinel file .fpm-watch.stop exists, or - The process receives an external termination (e.g., Ctrl+C).
Each iteration performs: 1. Sleep for poll seconds. 2. Scan for changes (fingerprints). 3. If changes were found, sleep for debounce seconds and rescan. 4. If fpm.toml changed, rebuild watch list. 5. Otherwise, run the computed fpm command (with target injection for run/test), notify plugins, and accept fingerprints.
Type Bound
watcher_t
Arguments
Type Intent Optional Attributes Name
class(watcher_t), intent(inout) :: self
Calls
Source Code
   subroutine watcher_run(self)
      class(watcher_t), intent(inout) :: self
      integer :: changed_count
      type(string_t), allocatable :: changed(:)
      character(len=:), allocatable :: cmd
      integer :: exitstat, j, idx
      real :: secs
      integer(int64) :: rate, t_last_rescan, t_now
      real :: dt
      if (self%cfg%w%once) return
      call system_clock(count_rate=rate)
      if (rate <= 0_int64) rate = 1000_int64
      call system_clock(t_last_rescan)
      do
         if (exists(".fpm-watch.stop")) exit
         call sleep_seconds(self%cfg%w%poll)
         call scan_changes(self%files, self%fp_prev, self%fp_now, self%changed_idx, changed_count)
         if (changed_count > 0) then
            call sleep_seconds(self%cfg%w%debounce)
            call scan_changes(self%files, self%fp_prev, self%fp_now, self%changed_idx, changed_count)
         end if
         if (changed_count > 0) then
            if (any_manifest_changed(self%files, self%changed_idx, changed_count)) then
               call handle_manifest_change(self)
               cycle
            end if
            allocate(changed(changed_count))
            do j = 1, changed_count
               idx = self%changed_idx(j)
               if (idx >= 1 .and. idx <= size(self%files)) then
                  changed(j)%s = self%files(idx)%s
               else
                  changed(j)%s = ""
               end if
            end do
            call self%fm%on_change_detected_all(changed)
            call report_changes(self%files, self%changed_idx, changed_count, self%cfg%w)
            cmd = build_run_command( &
               settings      = self%cfg%settings,    &
               full_cmdline  = self%cfg%fpm_cmdline, &
               cmd_prefix    = self%cfg%cmd_prefix,  &
               cmd_rest      = self%cfg%cmd_rest,    &
               roots         = self%roots,           &
               file_mask     = self%file_mask,       &
               changed_idx   = self%changed_idx,     &
               changed_count = changed_count )
            call self%fm%on_before_run_all(cmd)
            call run_command_and_report(cmd, self%cfg%w, exitstat, secs)
            call self%fm%on_after_run_all(exitstat, secs)
            call accept_changes(self%fp_prev, self%fp_now, self%changed_idx, changed_count)
            deallocate(changed)
         end if
         if (self%cfg%w%rescan > 0.0) then
            call system_clock(t_now)
            if (t_now < t_last_rescan) then
               t_last_rescan = t_now
            else
               dt = real(t_now - t_last_rescan) / real(rate)
               if (dt >= self%cfg%w%rescan) then
                  call log_info(self%cfg%w, "rescan triggered -> rebuilding watch list")
                  call rebuild_watch_list(self, print_header=.false.)
                  call system_clock(t_last_rescan)
               end if
            end if
         end if
      end do
   end subroutine watcher_run
Call graph
watcher_run calls exists, accept_changes, any_manifest_changed, build_run_command, handle_manifest_change, log_info, on_after_run_all, on_before_run_all, on_change_detected_all, rebuild_watch_list, report_changes, run_command_and_report, scan_changes, sleep_seconds
any_manifest_changed calls basename
build_run_command calls inject_names_into_cmd
handle_manifest_change calls log_info, rebuild_watch_list, manifest_key_from_files, on_manifest_changed_all
log_info calls colorize
on_after_run_all calls feat_after_noop
on_before_run_all calls feat_before_noop
on_change_detected_all calls feat_change_noop
rebuild_watch_list calls log_info, compute_watch_files_from_settings, ftoa, init_fingerprints, manifest_key_from_files, on_watch_list_built_all, print_banner, print_file_list, str
report_changes calls colorize, ftoa, str
run_command_and_report calls colorize, ftoa, run, str
scan_changes calls file_fingerprint
sleep_seconds calls sleep_os, sleep_spin
compute_watch_files_from_settings calls log_info, basename, ftoa, str, add, build_model, dep, get_package_data, is_executable_target, join_path, new_dependency_tree, dfs_mark_bool, dfs_mark_mask, filter_watch_files, gather_files_with_mask, is_run_or_test, normalize_path, push_file_with_mask, select_names_or_all, trim_or_empty, targets_from_sources
file_fingerprint calls hash_block
init_fingerprints calls file_fingerprint
manifest_key_from_files calls basename, file_fingerprint, features, fnv1a_mix_i64, fnv1a_mix_str
on_manifest_changed_all calls feat_manifest_noop
on_watch_list_built_all calls feat_list_noop
print_banner calls colorize, ftoa, str, active_features, active_profile, command_mode, trim_or_default
print_file_list calls colorize, str
sleep_os calls get_os_type, sleep_os_posix, sleep_os_win
active_features calls join_csv
active_profile calls trim_or_default
dfs_mark_bool calls dfs_mark_bool, dependencies, find_ptr_index
dfs_mark_mask calls dfs_mark_mask, dependencies, find_ptr_index
filter_watch_files calls basename, normalize_path, glob
fnv1a_mix_str calls fnv1a_mix_i64
gather_files_with_mask calls include_dependencies, vec_push_unique
hash_block calls fnv1a_mix_i64
push_file_with_mask calls vec_push_unique
select_names_or_all calls basename, is_executable_target, glob
sleep_os_posix calls c_nanosleep
sleep_os_win calls c_sleep_ms
vec_push_unique calls exists, normalize_path, is_ignored_path, is_in_dep_dirs, vec_grow
is_ignored_path calls normalize_path, contains_path_fragment, starts_with
is_in_dep_dirs calls normalize_path, starts_with
contains_path_fragment calls ends_with