watcher_init – fpm-watch
watcher_init Subroutine
MIT
13 statements
Source File
private subroutine watcher_init(self, cfg)
Initialize a watcher instance from configuration.
This routine: - Applies low-CPU mode selection to the sleep implementation. - Enables requested feature plugins and calls their init/start callbacks. - Builds the initial watch list and fingerprints. - Optionally performs an initial run (w%run_on_start).
Type Bound
watcher_t
Arguments
Type Intent Optional Attributes Name
class(watcher_t), intent(inout) :: self
type(watch_config_t), intent(in) :: cfg
Calls
Source Code
   subroutine watcher_init(self, cfg)
      class(watcher_t), intent(inout) :: self
      type(watch_config_t), intent(in) :: cfg
      self%cfg = cfg
      call set_low_cpu(self%cfg%w%low_cpu)
      call enable_features(self%fm, self%cfg%w)
      call self%fm%init_all(self%cfg)
      call self%fm%on_start_all()
      call rebuild_watch_list(self, print_header=.true.)
      if (self%cfg%w%run_on_start) then
         call run_once(self, trim(self%cfg%fpm_cmdline))
      end if
   end subroutine watcher_init
Call graph
watcher_init calls enable_features, init_all, on_start_all, rebuild_watch_list, run_once, set_low_cpu
enable_features calls add_stats, log_warn
init_all calls feat_init_noop
on_start_all calls feat_noop
rebuild_watch_list calls compute_watch_files_from_settings, ftoa, init_fingerprints, log_info, manifest_key_from_files, on_watch_list_built_all, print_banner, print_file_list, str
run_once calls on_after_run_all, on_before_run_all, run_command_and_report
add_stats calls fm_add, new_stats_feature
compute_watch_files_from_settings calls ftoa, log_info, str, add, basename, build_model, dep, get_package_data, is_executable_target, join_path, new_dependency_tree, dfs_mark_bool, dfs_mark_mask, filter_watch_files, gather_files_with_mask, is_run_or_test, normalize_path, push_file_with_mask, select_names_or_all, trim_or_empty, targets_from_sources
init_fingerprints calls file_fingerprint
log_info calls colorize
log_warn calls colorize
manifest_key_from_files calls basename, features, file_fingerprint, fnv1a_mix_i64, fnv1a_mix_str
on_after_run_all calls feat_after_noop
on_before_run_all calls feat_before_noop
on_watch_list_built_all calls feat_list_noop
print_banner calls ftoa, str, colorize, active_features, active_profile, command_mode, trim_or_default
print_file_list calls str, colorize
run_command_and_report calls ftoa, str, colorize, run
active_features calls join_csv
active_profile calls trim_or_default
dfs_mark_bool calls dfs_mark_bool, dependencies, find_ptr_index
dfs_mark_mask calls dfs_mark_mask, dependencies, find_ptr_index
file_fingerprint calls hash_block
filter_watch_files calls basename, normalize_path, glob
fnv1a_mix_str calls fnv1a_mix_i64
gather_files_with_mask calls include_dependencies, vec_push_unique
push_file_with_mask calls vec_push_unique
select_names_or_all calls basename, is_executable_target, glob
hash_block calls fnv1a_mix_i64
vec_push_unique calls normalize_path, exists, is_ignored_path, is_in_dep_dirs, vec_grow
is_ignored_path calls normalize_path, contains_path_fragment, starts_with
is_in_dep_dirs calls normalize_path, starts_with
contains_path_fragment calls ends_with